In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
df.shape

(150000, 32)

In [4]:
test.shape

(69129, 31)

In [5]:
train = pd.concat([df, test])

In [6]:
train.head()

,id,Time,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat8,feat9,feat10,feat11,feat12,feat13,feat14,feat15,feat16,feat17,feat18,feat19,feat20,feat21,feat22,feat23,feat24,feat25,feat26,feat27,feat28,Transaction_Amount,IsFraud
0,0,0.0,2.074329,-0.129425,-1.137418,0.412846,-0.192638,-1.210144,0.110697,-0.263477,0.742144,0.108782,-1.070243,-0.234910,-1.099360,0.502467,0.169318,0.065688,-0.306957,-0.323800,0.103348,-0.292969,-0.334701,-0.887840,0.336701,-0.110835,-0.291459,0.207733,-0.076576,-0.059577,1.98,0.0
1,1,0.0,1.998827,-1.250891,-0.520969,-0.894539,-1.122528,-0.270866,-1.029289,0.050198,-0.109948,0.908773,0.836798,-0.056580,-0.120990,-0.144028,-0.039582,1.653057,-0.253599,-0.814354,0.716784,0.065717,0.054848,-0.038367,0.133518,-0.461928,-0.465491,-0.464655,-0.009413,-0.038238,84.00,0.0
2,2,0.0,0.091535,1.004517,-0.223445,-0.435249,0.667548,-0.988351,0.948146,-0.084789,-0.042027,-0.818383,-0.376512,-0.226546,-0.552869,-0.886466,-0.180890,0.230286,0.590579,-0.321590,-0.433959,-0.021375,-0.326725,-0.803736,0.154495,0.951233,-0.506919,0.085046,0.224458,0.087356,2.69,0.0
3,3,0.0,1.979649,-0.184949,-1.064206,0.120125,-0.215238,-0.648829,-0.087826,-0.035367,0.885838,-0.007527,0.637441,0.676960,-1.504823,0.554039,-0.824356,-0.527267,-0.095838,-0.312519,0.642659,-0.340089,-0.095514,-0.079792,0.167701,-0.042939,0.000799,-0.096148,-0.057780,-0.073839,1.00,0.0
4,4,0.0,1.025898,-0.171827,1.203717,1.243900,-0.636572,1.099074,-0.938651,0.569239,0.692665,-0.097495,1.338869,1.391399,-0.128167,-0.081836,0.100548,-0.338937,0.090864,-0.423645,-0.731939,-0.203628,0.099157,0.608908,0.027901,-0.262813,0.257834,-0.252829,0.108338,0.021051,1.00,0.0

In [7]:
train.select_dtypes(exclude=['int', 'float']).columns

Index([], dtype='object')

In [8]:
train.isnull().sum()

id                        0
Time                      0
feat1                     0
feat2                     0
feat3                     0
feat4                     0
feat5                     0
feat6                     0
feat7                     0
feat8                     0
feat9                     0
feat10                    0
feat11                    0
feat12                    0
feat13                    0
feat14                    0
feat15                    0
feat16                    0
feat17                    0
feat18                    0
feat19                    0
feat20                    0
feat21                    0
feat22                    0
feat23                    0
feat24                    0
feat25                    0
feat26                    0
feat27                    0
feat28                    0
Transaction_Amount        0
IsFraud               69129
dtype: int64

In [9]:
target = pd.DataFrame(train['IsFraud'])
train.IsFraud.unique()

array([ 0.,  1., nan])

In [10]:
target.shape

(219129, 1)

In [11]:
train.shape

(219129, 32)

In [12]:
train.drop(columns=['id', 'Time'], inplace = True)

In [13]:
train.drop(columns=['IsFraud'], inplace = True)

In [14]:
train.head()

,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat8,feat9,feat10,feat11,feat12,feat13,feat14,feat15,feat16,feat17,feat18,feat19,feat20,feat21,feat22,feat23,feat24,feat25,feat26,feat27,feat28,Transaction_Amount
0,2.074329,-0.129425,-1.137418,0.412846,-0.192638,-1.210144,0.110697,-0.263477,0.742144,0.108782,-1.070243,-0.234910,-1.099360,0.502467,0.169318,0.065688,-0.306957,-0.323800,0.103348,-0.292969,-0.334701,-0.887840,0.336701,-0.110835,-0.291459,0.207733,-0.076576,-0.059577,1.98
1,1.998827,-1.250891,-0.520969,-0.894539,-1.122528,-0.270866,-1.029289,0.050198,-0.109948,0.908773,0.836798,-0.056580,-0.120990,-0.144028,-0.039582,1.653057,-0.253599,-0.814354,0.716784,0.065717,0.054848,-0.038367,0.133518,-0.461928,-0.465491,-0.464655,-0.009413,-0.038238,84.00
2,0.091535,1.004517,-0.223445,-0.435249,0.667548,-0.988351,0.948146,-0.084789,-0.042027,-0.818383,-0.376512,-0.226546,-0.552869,-0.886466,-0.180890,0.230286,0.590579,-0.321590,-0.433959,-0.021375,-0.326725,-0.803736,0.154495,0.951233,-0.506919,0.085046,0.224458,0.087356,2.69
3,1.979649,-0.184949,-1.064206,0.120125,-0.215238,-0.648829,-0.087826,-0.035367,0.885838,-0.007527,0.637441,0.676960,-1.504823,0.554039,-0.824356,-0.527267,-0.095838,-0.312519,0.642659,-0.340089,-0.095514,-0.079792,0.167701,-0.042939,0.000799,-0.096148,-0.057780,-0.073839,1.00
4,1.025898,-0.171827,1.203717,1.243900,-0.636572,1.099074,-0.938651,0.569239,0.692665,-0.097495,1.338869,1.391399,-0.128167,-0.081836,0.100548,-0.338937,0.090864,-0.423645,-0.731939,-0.203628,0.099157,0.608908,0.027901,-0.262813,0.257834,-0.252829,0.108338,0.021051,1.00

In [15]:
train.shape

(219129, 29)

In [16]:
# from scipy.stats import yeojohnson

In [17]:
# skewed = []

# for i in train.columns:
#     if abs(scipy.stats.skew(train[i])) >= 0.5:
#         print(i, scipy.stats.skew(train[i]))
#         skewed.append(i)
#         train[i] = yeojohnson(train[i])
#         print("after log",i, scipy.stats.skew(train[i]))

In [18]:
train.head()

,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat8,feat9,feat10,feat11,feat12,feat13,feat14,feat15,feat16,feat17,feat18,feat19,feat20,feat21,feat22,feat23,feat24,feat25,feat26,feat27,feat28,Transaction_Amount
0,2.074329,-0.129425,-1.137418,0.412846,-0.192638,-1.210144,0.110697,-0.263477,0.742144,0.108782,-1.070243,-0.234910,-1.099360,0.502467,0.169318,0.065688,-0.306957,-0.323800,0.103348,-0.292969,-0.334701,-0.887840,0.336701,-0.110835,-0.291459,0.207733,-0.076576,-0.059577,1.98
1,1.998827,-1.250891,-0.520969,-0.894539,-1.122528,-0.270866,-1.029289,0.050198,-0.109948,0.908773,0.836798,-0.056580,-0.120990,-0.144028,-0.039582,1.653057,-0.253599,-0.814354,0.716784,0.065717,0.054848,-0.038367,0.133518,-0.461928,-0.465491,-0.464655,-0.009413,-0.038238,84.00
2,0.091535,1.004517,-0.223445,-0.435249,0.667548,-0.988351,0.948146,-0.084789,-0.042027,-0.818383,-0.376512,-0.226546,-0.552869,-0.886466,-0.180890,0.230286,0.590579,-0.321590,-0.433959,-0.021375,-0.326725,-0.803736,0.154495,0.951233,-0.506919,0.085046,0.224458,0.087356,2.69
3,1.979649,-0.184949,-1.064206,0.120125,-0.215238,-0.648829,-0.087826,-0.035367,0.885838,-0.007527,0.637441,0.676960,-1.504823,0.554039,-0.824356,-0.527267,-0.095838,-0.312519,0.642659,-0.340089,-0.095514,-0.079792,0.167701,-0.042939,0.000799,-0.096148,-0.057780,-0.073839,1.00
4,1.025898,-0.171827,1.203717,1.243900,-0.636572,1.099074,-0.938651,0.569239,0.692665,-0.097495,1.338869,1.391399,-0.128167,-0.081836,0.100548,-0.338937,0.090864,-0.423645,-0.731939,-0.203628,0.099157,0.608908,0.027901,-0.262813,0.257834,-0.252829,0.108338,0.021051,1.00

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler = StandardScaler()
scaler.fit(train)

StandardScaler()

In [21]:
train2 = pd.DataFrame(scaler.transform(train), index=train.index, columns = train.columns)

In [22]:
train2.head()

,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat8,feat9,feat10,feat11,feat12,feat13,feat14,feat15,feat16,feat17,feat18,feat19,feat20,feat21,feat22,feat23,feat24,feat25,feat26,feat27,feat28,Transaction_Amount
0,1.417723,-0.129568,-1.540559,0.240731,-0.089637,-1.073174,0.216647,-0.465036,0.735630,0.166709,-1.327264,-0.270947,-0.951826,0.486854,0.015087,0.061103,-0.469709,-0.369522,0.150894,-0.688652,-0.718199,-1.400090,1.217046,-0.181829,-1.021451,0.417528,-0.388293,-0.466403,-0.426937
1,1.363615,-1.208037,-0.952477,-0.843640,-0.891189,-0.304684,-1.100912,-0.091033,-0.048362,1.158190,0.742179,-0.093317,-0.017751,-0.253896,-0.221197,1.966312,-0.394870,-0.994869,0.979942,0.127433,0.203208,0.020885,0.578455,-0.773794,-1.449321,-1.001415,-0.100477,-0.336961,0.116982
2,-0.003205,0.960901,-0.668644,-0.462696,0.651832,-0.891710,1.184544,-0.251981,0.014131,-0.982386,-0.574456,-0.262616,-0.430077,-1.104578,-0.381027,0.258658,0.789157,-0.366705,-0.575270,-0.070720,-0.699333,-1.259402,0.644384,1.608883,-1.551175,0.158620,0.901735,0.424868,-0.422228
3,1.349872,-0.182963,-1.470716,-0.002058,-0.109118,-0.613922,-0.012799,-0.193054,0.867840,0.022559,0.525845,0.637346,-1.338932,0.545945,-1.108841,-0.650580,-0.173597,-0.355142,0.879764,-0.795861,-0.152446,-0.048410,0.685889,-0.067352,-0.302912,-0.223754,-0.307748,-0.552913,-0.433436
4,0.666386,-0.170344,0.692845,0.930023,-0.472301,0.816161,-0.996156,0.527832,0.690105,-0.088943,1.287007,1.348982,-0.024604,-0.182637,-0.062698,-0.424540,0.088268,-0.496803,-0.977985,-0.485382,0.308014,1.103629,0.246506,-0.438073,0.329029,-0.554398,0.404124,0.022671,-0.433436

In [23]:
train3 = train2.iloc[:150000]

In [24]:
train3.shape

(150000, 29)

In [25]:
test = train2.iloc[150000:]

In [26]:
test.shape

(69129, 29)

In [27]:
target = target.iloc[:150000]
target

        IsFraud
0           0.0
1           0.0
2           0.0
3           0.0
4           0.0
...         ...
149995      0.0
149996      0.0
149997      0.0
149998      0.0
149999      0.0

[150000 rows x 1 columns]

In [28]:
from pycaret.classification import *

In [29]:
_ = setup(data=pd.concat([train3, target], axis=1), target = 'IsFraud')

In [30]:
best_model = compare_models(sort='AUC')

In [31]:
tune_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [37]:
log_reg = create_model('lr')

In [32]:
s = pd.read_csv("sample_submission.csv")

In [33]:
s.head()

       id  IsFraud
0  150000      0.5
1  150001      0.5
2  150002      0.5
3  150003      0.5
4  150004      0.5

In [34]:
test.head()

,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat8,feat9,feat10,...,feat20,feat21,feat22,feat23,feat24,feat25,feat26,feat27,feat28,Transaction_Amount
0,-0.556994,-0.362085,-0.087276,0.690987,1.855621,0.194149,-0.534774,-0.453790,0.062883,0.966293,...,0.395550,-0.525717,0.531139,-0.324660,0.773837,-1.543084,0.522737,-2.017188,-1.918204,-0.238336
1,-0.856340,-0.927700,-0.145500,0.482143,1.016482,-1.388796,0.764310,0.159201,0.105749,0.560877,...,0.739572,0.381223,1.217410,-0.347419,-1.070680,-0.977111,1.479851,1.439584,0.751679,-0.287542
2,0.631366,-0.265699,-0.005653,-1.124009,0.901798,-0.603918,-1.012808,-1.929527,0.261533,-1.419217,...,0.787268,1.298504,2.050717,-0.865452,-0.606381,0.447539,-0.010663,0.100083,0.248144,0.872976
3,0.774425,-0.222263,-0.690733,-0.088825,1.027901,0.922885,-1.676264,-0.699079,0.742089,-0.621947,...,-0.369314,-0.173935,0.091422,0.085962,-0.767741,0.878749,-0.825754,0.283394,0.061015,-0.373818
4,0.507961,-0.267606,0.460256,-1.028624,0.417544,0.399533,1.313683,-1.463875,0.113951,-0.473658,...,-0.312899,0.045449,0.216444,-0.600833,0.022124,0.439123,-0.568620,0.038965,0.240476,1.144869

In [40]:
evaluate_model(log_reg)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [38]:
# from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
# m = QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0, store_covariance=False, tol=0.0001)
# m.fit(train3, target)
s['IsFraud'] = tune_model.predict(test)

In [39]:
s.to_csv('submission3.csv', index=False, header=True)